### ISSUE TITLE
Have you tried voice reconstruction at 24kHz ？

### ISSUE THREAD

**Issue by lliwons** [YangAi520/APNet#1]
Thank you for making your code publicly available!

Have you ever tried speech reconstruction at 24kHz or higher sampling rates?

**Comment by YangAi520** [comment]
> Thank you for making your code publicly available!
> 
> Have you ever tried speech reconstruction at 24kHz or higher sampling rates?

Hello, Thanks for your attention to our work. Current codes may only support speech generation at 16kHz. The generated results at higher sampling rates may not be very good, and this may be due to the higher-frequency phases being more difficult to predict directly. Addressing this issue is one of our ongoing tasks, please continue to follow our work.
